import {addGardenPeople} from './garden-people.js?v=3'
import {HONEY_FILE,birthdayGreeting,birthdayName} from './garden-characters.mjs?v=3'
import * as THREE from './vendor/three/build/three.module.js'

// A self-contained, locally rendered garden. No game-scene globals or network assets.
export function createLivingHome({container,onMessage,reducedMotion=false}) {
 const scene=new THREE.Scene();scene.background=new THREE.Color('#84e4eb');scene.fog=new THREE.Fog('#84e4eb',65,155)
 const renderer=new THREE.WebGLRenderer({antialias:true,alpha:false,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=.95;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;container.append(renderer.domElement)
 const camera=new THREE.OrthographicCamera(-26,26,16,-16,.1,200);camera.position.set(0,25,38);camera.lookAt(0,1,-1)
 scene.add(new THREE.HemisphereLight('#e6ffff','#188c72',.85));const sun=new THREE.DirectionalLight('#fff3d0',2.0);sun.position.set(-18,35,18);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-30,right:30,top:26,bottom:-24,near:1,far:90});sun.shadow.normalBias=.05;scene.add(sun)
 const fill=new THREE.DirectionalLight('#83caff',.5);fill.position.set(20,10,-20);scene.add(fill)
 let clock=0,active=true,quiet=reducedMotion,width=0,height=0,pan=0,seed=258,motionPaused=false
 const partyState={active:false}
 const sunColor=sun.color.clone(),fillColor=fill.color.clone()
 const callbacks=[],hits=[],hotspots=[],bursts=[],buckets=new Map(),materials=new Map(),wind={value:0}
 const rnd=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296}
 const sphere=new THREE.SphereGeometry(1,16,12),boxGeo=new THREE.BoxGeometry(1,1,1),cylinder=new THREE.CylinderGeometry(1,1,1,12),cone=new THREE.ConeGeometry(1,1,12)
 function mat(color,rough=.65){const key=color+rough;if(!materials.has(key))materials.set(key,new THREE.MeshStandardMaterial({color,roughness:rough}));return materials.get(key)}
 function mesh(parent,geo,color,p=[0,0,0],s=[1,1,1]){const o=new THREE.Mesh(geo,typeof color==='string'?mat(color):color);o.position.set(...p);o.scale.set(...s);o.castShadow=true;o.receiveShadow=true;parent.add(o);return o}
 function ball(parent,color,p,s){return mesh(parent,sphere,color,p,s)}
 function group(parent,p=[0,0,0]){const g=new THREE.Group();g.position.set(...p);parent.add(g);return g}
 function rod(parent,a,b,r,color){const A=new THREE.Vector3(...a),B=new THREE.Vector3(...b),d=B.clone().sub(A);const o=mesh(parent,cylinder,color,A.clone().add(B).multiplyScalar(.5).toArray(),[r,d.length(),r]);o.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),d.normalize());return o}
 function batch(geo,color,p,s=[1,1,1],rot=[0,0,0],sway=false){const key=geo.uuid+color+sway;if(!buckets.has(key))buckets.set(key,{geo,color,sway,items:[]});buckets.get(key).items.push({p,s,rot})}
 function leaf(p,s,color,rot=[0,0,0]){batch(sphere,color,p,s,rot,true)}
 function textSign(text,p,w=2.7,color='#083d4c'){const c=document.createElement('canvas');c.width=512;c.height=128;const x=c.getContext('2d');x.fillStyle='#ecfff1';x.beginPath();x.roundRect(2,2,508,124,28);x.fill();x.fillStyle=color;let fs=34;x.font=`600 ${fs}px Arial`;while(x.measureText(text).width>470&&fs>14)x.font=`600 ${--fs}px Arial`;x.textAlign='center';x.textBaseline='middle';x.fillText(text,256,64);const tex=new THREE.CanvasTexture(c);tex.colorSpace=THREE.SRGBColorSpace;const o=new THREE.Sprite(new THREE.SpriteMaterial({map:tex,depthTest:true}));o.position.set(...p);o.scale.set(w,w/4,1);scene.add(o);return o}
 function surprise(id,label,target,fn){target.traverse(o=>{if(o.isMesh){o.userData.surprise=id;hits.push(o)}});hotspots.push({id,label,target,run:()=>{fn();return label}})}
 function burst(p,color='#ff669b',count=18){if(quiet){return}for(let i=0;i<count;i++){const o=ball(scene,color,p,[.08,.08,.08]);o.castShadow=false;bursts.push({o,life:1.7,v:new THREE.Vector3((rnd()-.5)*3,1.3+rnd()*2,(rnd()-.5)*2)})}}
 // Turquoise water with gently moving geometric swells and sunlit ripples.
 const waterGeo=new THREE.PlaneGeometry(180,150,100,70);waterGeo.rotateX(-Math.PI/2);const water=mesh(scene,waterGeo,mat('#11bdc8',.27),[0,-1.15,-30]);water.castShadow=false;const original=waterGeo.attributes.position.array.slice()
 callbacks.push(t=>{const a=waterGeo.attributes.position;for(let i=0;i<a.count;i++)a.setY(i,original[i*3+1]+Math.sin(original[i*3]*.42+t*.65)*.075+Math.sin(original[i*3+2]*.6+t*.8)*.055);a.needsUpdate=true})
 const island=mesh(scene,new THREE.CylinderGeometry(24,24.8,1.8,96), '#f5dfa2',[0,-1.2,0],[1,1,.59]);const grass=mesh(scene,new THREE.CylinderGeometry(22.3,23.5,.7,96),'#59d4a0',[0,-.1,-1],[1,1,.58]);
 // Shallow tide pools, stepping stones, and a quiet central terrace.
 mesh(scene,new THREE.CylinderGeometry(7.1,7.4,.35,64),'#e7fbd9',[0,.31,2],[1,1,.72]);mesh(scene,new THREE.CylinderGeometry(6.8,6.9,.15,64),'#a5e9d3',[0,.56,2],[1,1,.72]);
 for(let i=0;i<9;i++)batch(cylinder,'#e2f3c9',[Math.sin(i*.6)*.4,.3,6+i*.58],[.65,.15,.38],[0,rnd(),0])
 for(let i=0;i<30;i++){const a=i/30*Math.PI*2;batch(sphere,'#f3ebbc',[Math.cos(a)*23.5,-.65,Math.sin(a)*13.8],[.2+rnd()*.35,.1,.16+rnd()*.3])}
 // Fine surf lines trace the beach; a little paper boat answers a click.
 const surf=new THREE.Group();scene.add(surf)
 for(let j=0;j<3;j++){const pts=[];for(let k=0;k<=100;k++){const a=k/100*Math.PI*2;pts.push(new THREE.Vector3(Math.cos(a)*(25.1+j*.65),-.95,Math.sin(a)*(14.8+j*.4)))}const wave=new THREE.Line(new THREE.BufferGeometry().setFromPoints(pts),new THREE.LineBasicMaterial({color:'#d2fff6',transparent:true,opacity:.5-j*.12}));surf.add(wave)}callbacks.push(t=>{surf.scale.setScalar(1+Math.sin(t*.5)*.007)})
 const boat=group(scene,[19,-.55,15]);const hull=mesh(boat,new THREE.ConeGeometry(.7,1.4,4),'#fffbd5',[0,0,0],[1,.35,1]);hull.rotation.z=Math.PI;rod(boat,[0,0,0],[0,1.35,0],.025,'#098f9a');const sailGeo=new THREE.BufferGeometry();sailGeo.setAttribute('position',new THREE.Float32BufferAttribute([0,.3,0,0,1.3,0,.85,.3,0],3));sailGeo.computeVertexNormals();const sailMat=mat('#ff8cb5').clone();sailMat.side=THREE.DoubleSide;mesh(boat,sailGeo,sailMat);let boatUntil=0;surprise('boat','Send a little love boat',boat,()=>{boatUntil=clock+5;burst(boat.position.toArray(),'#ff9ebe');onMessage('A boatful of love, setting sail for wherever your next adventure takes you.')});callbacks.push(t=>{boat.rotation.z=Math.sin(t*1.4)*.08;boat.position.y=-.55+Math.sin(t)*.06;boat.position.x=19+(t<boatUntil?Math.sin((boatUntil-t)/5*Math.PI)*2:0)})
 // A low water garden brings gentle movement to the clearing below the greeting.
 const pool=mesh(scene,new THREE.CylinderGeometry(2.2,2.3,.2,48),'#028f9b',[0,.68,3],[1,1,.65]);const poolWater=mesh(scene,new THREE.CylinderGeometry(2.05,2.05,.05,48),'#18c8cf',[0,.81,3],[1,1,.65]);
 for(let j=0;j<3;j++){const ring=mesh(scene,new THREE.TorusGeometry(.45+j*.42,.012,5,48),'#bcfff0',[0,.85,3]);ring.rotation.x=-Math.PI/2;ring.scale.y=.65;callbacks.push(t=>{ring.scale.setScalar(1+Math.sin(t+j)*.07)})}
 const lotus=group(scene,[.6,.88,3]);for(let i=0;i<7;i++){const a=i/7*6.28;const petal=ball(lotus,i%2?'#ff5da4':'#ffa1cf',[Math.cos(a)*.3,.08,Math.sin(a)*.3],[.3,.1,.14]);petal.rotation.y=-a}ball(lotus,'#ffe74d',[0,.15,0],[.18,.1,.18]);surprise('lotus','Make a birthday wish',lotus,()=>{burst([.6,1.2,3],'#ff81c2',25);onMessage('A quiet birthday wish: more beach days, more forest walks, more time with your favourite people.')});callbacks.push(t=>lotus.rotation.y=Math.sin(t*.4)*.12)
 // Hills and a layered forest across the lagoon.
 for(let i=0;i<13;i++)ball(scene,['#159d95','#22bba5','#31caba'][i%3],[-55+i*9,-1,-43-rnd()*12],[5+rnd()*5,3+rnd()*5,4+rnd()*4])
 for(let i=0;i<10;i++){const cloud=group(scene,[-48+i*11,11+rnd()*6,-55-rnd()*12]);for(let j=0;j<3;j++)ball(cloud,'#dffffa',[j*1.6,Math.sin(j)*.5,0],[1.9,1,1]);callbacks.push(t=>{cloud.position.x=-48+i*11+Math.sin(t*.025+i)*2})}
 function tree(x,z,h,kind=0){const g=group(scene,[x,0,z]);rod(g,[0,0,0],[.2,h,0],.22,kind?'#297866':'#39897b');for(let k=0;k<4;k++){const a=k*2.4,end=[Math.cos(a)*1.3,h*(.6+k*.08),Math.sin(a)*1.1];rod(g,[.12,h*.45,0],end,.10,'#39897b')}
 for(let j=0;j<28;j++){const a=rnd()*6.28,r=rnd()*2.7;leaf([x+Math.cos(a)*r,h*.68+rnd()*h*.32,z+Math.sin(a)*r*.7],[.5+rnd()*.7,.16+rnd()*.25,.24+rnd()*.25],['#087f7a','#0ca794','#35c9a1','#b8e57e'][j%4],[rnd()*.8,rnd()*6.28,rnd()*.5])}return g}
 for(const [x,z,h] of [[-20,-4,8],[-16,-6,10],[-12,-8,7],[-21,3,6],[19,-5,10],[15,-8,8],[21,1,7],[-7,-10,6],[8,-10,6]])tree(x,z,h)
 // Palm fronds form a natural canopy rather than an enclosing room.
 function palm(x,z,h){const g=group(scene,[x,0,z]);rod(g,[0,0,0],[.6,h,0],.21,'#58a58a');for(let k=0;k<7;k++){const a=k/7*6.28;for(let j=0;j<7;j++){const r=.45+j*.42;leaf([x+.6+Math.cos(a)*r,h+.7-Math.pow(j/6,2)*1.8,z+Math.sin(a)*r],[.72,.09,.23],j%2?'#13ae89':'#61d39c',[0,-a,Math.sin(a)*.18])}}}
 palm(-23,7,7.5);palm(22,7,8)
 // Teal pergola frames the centre; its climbing blooms remain outside the text.
 for(const x of [-7.8,7.8]){rod(scene,[x,0,-3],[x,7.5,-3],.12,'#067d83');rod(scene,[x,7.5,-3],[x*.75,8.1,-3],.1,'#067d83');for(let j=0;j<16;j++){const y=j*.45;leaf([x+Math.sin(j)*.4,y,-2.95],[.45,.10,.20],j%2?'#a3ef83':'#18bfa1',[0,j,.3]);if(j%3===0)ball(scene,'#fa74ab',[x+.28,y,-2.7],[.16,.18,.16])}}
 function flower(x,z,size,color){const y=.15;batch(cylinder,'#229d73',[x,y+size*.6,z],[.025,size*1.2,.025],[0,0,.1],true);leaf([x+.13,y+size*.3,z],[.27,.055,.12],'#41c897',[0,0,.4]);for(let k=0;k<6;k++){const a=k/6*6.28;batch(sphere,color,[x+Math.cos(a)*size*.24,y+size*1.2,z+Math.sin(a)*size*.24],[size*.22,size*.10,size*.14],[0,-a,0],true)}batch(sphere,'#ffe77c',[x,y+size*1.25,z],[size*.15,size*.1,size*.15],[],true)}
 for(let i=0;i<105;i++){const side=i%2?-1:1,x=side*(8+rnd()*13),z=-6+rnd()*17;flower(x,z,.4+rnd()*.7,['#ff73af','#ffd85e','#9885ef','#fb9a6b','#f2ffff'][i%5])}
 // Shells and tide-pool treasures.
 for(let i=0;i<14;i++){const x=-20+rnd()*40,z=11+rnd()*2;batch(sphere,i%2?'#ffe5c7':'#e4b7e5',[x,-.4,z],[.22,.1,.16],[0,rnd()*6,0])}
 const shell=group(scene,[15,-.1,10]);for(let j=0;j<9;j++){const a=(j/8-.5)*2;const o=ball(shell,j%2?'#ffc8d1':'#ffe4ca',[Math.sin(a)*.6,.2,Math.cos(a)*.35],[.16,.12,.65]);o.rotation.y=a}let shellUntil=0;surprise('shell','Listen to the sea',shell,()=>{shellUntil=clock+4;burst([15,.6,10],'#a5ffff');onMessage('A little sea breeze, just for you. Take a breath. You’re home.');seaSound()});callbacks.push(t=>{shell.rotation.y=Math.sin(t*.4)*.05+(shellUntil>t?Math.sin(t*4)*.12:0)})
 // Birds: articulated wings, tails, beaks and curious head movements.
 function bird(name,x,y,z,bodyColor,wingColor,crest=false){const g=group(scene,[x,y,z]);ball(g,bodyColor,[0,.25,0],[.38,.47,.29]);const head=group(g,[0,.72,.02]);ball(head,bodyColor,[0,0,0],[.29,.3,.28]);ball(head,'#142a39',[-.115,.04,.25],[.04,.045,.035]);ball(head,'#142a39',[.115,.04,.25],[.04,.045,.035]);const beak=mesh(head,cone,'#ffc766',[0,-.08,.35],[.105,.3,.1]);beak.rotation.x=Math.PI/2;
 if(crest)for(let i=0;i<4;i++){const o=ball(head,'#ffe568',[(i-1.5)*.06,.3+i*.035,-.05],[.055,.24,.065]);o.rotation.x=-.4}
 const wings=[-1,1].map(s=>{const p=group(g,[s*.3,.43,0]);ball(p,wingColor,[s*.12,-.1,0],[.17,.37,.28]);return p});const tail=ball(g,wingColor,[0,-.03,-.38],[.17,.12,.45]);for(const s of [-1,1])rod(g,[s*.12,-.08,0],[s*.14,-.25,.08],.025,'#c89d61');let flyUntil=0
 surprise(name,name,g,()=>{flyUntil=clock+4;burst(g.position.clone().add(new THREE.Vector3(0,1,0)).toArray(),'#ffe881',12);onMessage(`${name} has a birthday song for Sam. You’re everybody’s favourite perch.`);chirp()})
 callbacks.push(t=>{const clicked=t<flyUntil,flight=clicked||partyState.active;g.position.y=y+(clicked?Math.sin((flyUntil-t)/4*Math.PI)*2:partyState.active?Math.abs(Math.sin(t*8+x))*1.4:Math.sin(t*1.6+x)*.045);head.rotation.z=Math.sin(t*.9+x)*.12;wings.forEach((w,i)=>w.rotation.z=(i?1:-1)*(flight?Math.sin(t*18)*.9:.06*Math.sin(t*2)));tail.rotation.x=Math.sin(t*1.8)*.05});return g}
 bird('Cockatoo',-13,4.6,-1,'#fffde6','#f2ead0',true);bird('Rainbow lorikeet',12,4.2,0,'#3d82ef','#17b981');bird('Kookaburra',-19,2.1,6,'#f7dfb4','#805b40');bird('Kingfisher',18,2.4,5,'#16bfe0','#087eaa');bird('Seagull',-13,.9,10,'#f7ffff','#9ebec6')
 rod(scene,[-15,3.9,-1],[-11,3.9,-1],.09,'#388974');rod(scene,[10,3.5,0],[14,3.5,0],.09,'#388974')
 // Honey: a cream-and-caramel cockalier, floppy ears and a very busy tail.
 const honey=group(scene,[-9,.4,8]);honey.rotation.y=.2;ball(honey,'#e7b775',[0,.65,0],[.65,.48,1]);ball(honey,'#fff0cd',[0,.68,.8],[.5,.5,.46]);const dogHead=group(honey,[0,1.08,.95]);ball(dogHead,'#edc48d',[0,0,0],[.48,.46,.45]);ball(dogHead,'#fff1d2',[0,-.13,.32],[.31,.25,.26]);ball(dogHead,'#342b2e',[0,-.08,.55],[.13,.10,.08]);for(const s of [-1,1]){ball(dogHead,'#342b2e',[s*.2,.08,.36],[.065,.08,.055]);ball(dogHead,'#fff',[s*.19,.105,.408],[.018,.022,.015])}const ears=[-1,1].map(s=>ball(dogHead,'#ad753f',[s*.44,-.15,0],[.21,.51,.3]));for(const x of [-.38,.38])for(const z of [-.6,.55]){ball(honey,'#f8ddb1',[x,.2,z],[.18,.4,.19]);ball(honey,'#fff0d6',[x,0,z+.06],[.22,.12,.25])}const tail=group(honey,[0,.83,-.8]);const tailFur=ball(tail,'#d59b5f',[0,.23,-.38],[.17,.20,.54]);tailFur.rotation.x=.4;mesh(honey,new THREE.TorusGeometry(.41,.04,8,24),'#00a9af',[0,.9,.63]).rotation.x=Math.PI/2;let dogUntil=0
 for(let i=0;i<12;i++){const a=i/12*Math.PI*2,o=ball(honey,i%3===0?'#c5ed5c':'#ff82b9',[Math.cos(a)*.58,.65,-.22+Math.sin(a)*.45],[.28,.08,.37]);o.rotation.y=-a;o.rotation.z=Math.cos(a)*.25}
 textSign('Honey with tutu',[-9,2.65,8],3.1)
 surprise('honey',`${birthdayName(HONEY_FILE)}: Happy Birthday Sammy`,honey,()=>{dogUntil=clock+5;burst([-9,1.7,8],'#ff79ab',24);onMessage(birthdayGreeting(HONEY_FILE));softNotes([392,494,587])})
 callbacks.push(t=>{const excited=dogUntil>t||partyState.active;tail.rotation.y=Math.sin(t*(excited?15:5))*(excited?.7:.28);dogHead.rotation.z=Math.sin(t*.8)*.09;ears.forEach((e,i)=>e.rotation.z=Math.sin(t*2+i)*.06);honey.position.y=.4+(partyState.active?Math.abs(Math.sin(t*7))*.4:dogUntil>t?Math.abs(Math.sin(t*6))*.25:0)})
 addGardenPeople({scene,group,ball,rod,mesh,sphere,boxGeo,cylinder,cone,surprise,callbacks,burst,onMessage,softNotes,textSign,getTime:()=>clock,partyState})
 mesh(scene,boxGeo,'#e5d9a2',[11,.32,6],[3.9,.16,.9]);for(const x of [9.5,12.5])rod(scene,[x,0,6],[x,.3,6],.09,'#087f87')
 // Love for the whole world: a small garden globe that blooms with connection.
 const globe=group(scene,[-15,1.2,3]);ball(globe,'#24a5d1',[0,.4,0],[.78,.78,.78]);for(let i=0;i<8;i++){const a=i*2.4;ball(globe,'#a2e47b',[Math.cos(a)*.63,.4+Math.sin(i)*.38,Math.sin(a)*.63],[.25,.18,.13])}const globeStand=mesh(scene,cylinder,'#087d91',[-15,.35,3],[.3,.7,.3]);let globeUntil=0;surprise('world','Send the world some love',globe,()=>{globeUntil=clock+5;burst([-15,2.1,3],'#ffe67e',28);onMessage('A little kindness travels a long way. You make this world a lovelier place, Sam.');softNotes([262,330,392,523])});callbacks.push(t=>{globe.rotation.y=t*(t<globeUntil?.8:.08)})
 // The kindness garden grows with attention. Repeated clicks revisit, never pile up objects.
 const kindness=group(scene,[16,.3,9]);const bloomGroups=[];for(let i=0;i<7;i++){const a=i*2.4,g=group(kindness,[Math.cos(a)*.7,0,Math.sin(a)*.5]);rod(g,[0,0,0],[0,.9,0],.04,'#0f9b78');for(let k=0;k<5;k++)ball(g,'#ff86ba',[Math.cos(k*1.256)*.22,.9,Math.sin(k*1.256)*.22],[.2,.1,.14]);ball(g,'#ffe974',[0,.92,0],[.13,.1,.13]);g.scale.setScalar(.4);bloomGroups.push(g)}textSign('GROW A LITTLE KINDNESS',[16,2.3,9],3.1);let growth=.4;surprise('kindness','Grow the kindness garden',kindness,()=>{growth=growth<.9?1:.4;burst([16,1.5,9],'#ffd86c');onMessage(growth===1?'One kind act. Seven new blooms. Imagine what a lifetime of your kindness grows.':'A fresh beginning. There’s always room for another kind act.')});callbacks.push(()=>bloomGroups.forEach(g=>g.scale.lerp(new THREE.Vector3(growth,growth,growth),quiet?1:.04)))
 // Butterflies in flight and an occasional birthday visitor overhead.
 for(let i=0;i<8;i++){const g=group(scene,[0,0,0]),w=[-1,1].map(s=>ball(g,i%2?'#ffc857':'#ff79bc',[s*.13,0,0],[.16,.025,.23]));ball(g,'#146a7c',[0,0,0],[.025,.035,.17]);callbacks.push(t=>{const a=t*.18+i*2.4;g.position.set(Math.cos(a)*(12+i%3),2.5+Math.sin(t*.7+i),Math.sin(a)*7);g.rotation.y=-a;w.forEach((m,k)=>m.rotation.z=(k?1:-1)*Math.sin(t*10+i)*.8)})}
 // Batch the static garden into instanced draws; wind moves the tips in the shader.
 for(const {geo,color,items,sway} of buckets.values()){let material=mat(color);if(sway){material=material.clone();material.onBeforeCompile=shader=>{shader.uniforms.gardenTime=wind;shader.vertexShader='uniform float gardenTime;\n'+shader.vertexShader;shader.vertexShader=shader.vertexShader.replace('#include <begin_vertex>','#include <begin_vertex>\n#ifdef USE_INSTANCING\ntransformed.x += sin(gardenTime * 1.2 + instanceMatrix[3].x * .8 + instanceMatrix[3].z) * .05 * (position.y + 1.0);\n#endif')};material.customProgramCacheKey=()=> 'garden-wind-v1'}const o=new THREE.InstancedMesh(geo,material,items.length),dummy=new THREE.Object3D();items.forEach((item,i)=>{dummy.position.set(...item.p);dummy.scale.set(...item.s);dummy.rotation.set(item.rot[0]||0,item.rot[1]||0,item.rot[2]||0);dummy.updateMatrix();o.setMatrixAt(i,dummy.matrix)});o.receiveShadow=true;o.castShadow=true;scene.add(o)}
 let audioContext
 function softNotes(notes){if(quiet||!document.querySelector('#garden-sound')?.checked)return;try{audioContext??=new (window.AudioContext||window.webkitAudioContext)();audioContext.resume();notes.forEach((f,i)=>{const o=audioContext.createOscillator(),v=audioContext.createGain(),t=audioContext.currentTime+i*.11;o.type='sine';o.frequency.value=f;v.gain.setValueAtTime(0,t);v.gain.linearRampToValueAtTime(.045,t+.025);v.gain.exponentialRampToValueAtTime(.001,t+.6);o.connect(v);v.connect(audioContext.destination);o.start(t);o.stop(t+.65)})}catch{}}
 function chirp(){softNotes([880,1320,1100,1568])}function seaSound(){if(quiet||!document.querySelector('#garden-sound')?.checked)return;try{audioContext??=new (window.AudioContext||window.webkitAudioContext)();audioContext.resume();const rate=audioContext.sampleRate,b=audioContext.createBuffer(1,rate*3,rate),a=b.getChannelData(0);for(let i=0;i<a.length;i++)a[i]=(Math.random()*2-1)*.4;const src=audioContext.createBufferSource(),filter=audioContext.createBiquadFilter(),gain=audioContext.createGain(),t=audioContext.currentTime;src.buffer=b;filter.type='lowpass';filter.frequency.value=750;gain.gain.setValueAtTime(0,t);gain.gain.linearRampToValueAtTime(.24,t+1);gain.gain.linearRampToValueAtTime(0,t+3);src.connect(filter);filter.connect(gain);gain.connect(audioContext.destination);src.start(t);src.stop(t+3)}catch{}}
 const ray=new THREE.Raycaster(),pointer=new THREE.Vector2();let down
 renderer.domElement.addEventListener('pointerdown',e=>{down=[e.clientX,e.clientY,container.scrollLeft]})
 renderer.domElement.addEventListener('pointerup',e=>{if(!active||!down||Math.hypot(e.clientX-down[0],e.clientY-down[1])>8||Math.abs(container.scrollLeft-down[2])>8)return;const rect=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1);ray.setFromCamera(pointer,camera);const hit=ray.intersectObjects(hits,false)[0];if(hit)trigger(hit.object.userData.surprise)})
 function trigger(id){const h=hotspots.find(h=>h.id===id);if(h){h.run();draw(0);return true}return false}
 // Ten seconds of nightclub takeover: coloured lights (draw()) and every character
 // jumping (their own callbacks, gated on partyState.active) already react on their
 // own — this just flips the switch and flips it back.
 let partyTimer=null
 function party(){if(partyState.active)return false;partyState.active=true;clearTimeout(partyTimer);partyTimer=setTimeout(()=>{partyState.active=false},10000);return true}
 function resize(center=false){const mobile=innerWidth<=700;const previous=center?.5:width>innerWidth?(container.scrollLeft/(width-innerWidth)):.5;width=mobile?Math.max(1200,innerWidth*2.8):innerWidth;height=innerHeight;renderer.setSize(width,height);camera.left=-26;camera.right=26;camera.top=26*height/width;camera.bottom=-camera.top;camera.updateProjectionMatrix();container.scrollLeft=mobile?(width-innerWidth)*previous:0;draw(0)}
 function draw(dt){if(!active||((quiet||motionPaused)&&dt>0))return;if(!quiet&&!motionPaused)clock+=dt;wind.value=quiet||motionPaused?0:clock
 if(partyState.active&&!quiet){const hue=(clock*.6)%1;sun.color.setHSL(hue,.85,.6);fill.color.setHSL((hue+.5)%1,.85,.6)}else{sun.color.copy(sunColor);fill.color.copy(fillColor)}
 for(const fn of callbacks)fn(quiet?0:clock);for(let i=bursts.length-1;i>=0;i--){const b=bursts[i];if(!quiet&&!motionPaused){b.life-=dt;b.v.y-=dt*1.2;b.o.position.addScaledVector(b.v,dt);b.o.scale.setScalar(.08*Math.max(0,b.life/1.7))}if(b.life<=0||quiet){scene.remove(b.o);bursts.splice(i,1)}}renderer.render(scene,camera)}
 renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();onMessage('The garden is taking a breather. Your birthday journey and all four portals are still here.')})
 resize()
 return {draw,resize,trigger,party,hotspots:hotspots.map(({id,label})=>({id,label})),setActive(v){active=v},setReduced(v){quiet=v;draw(0)},setPaused(v){motionPaused=v;draw(0)},snapshot(){draw(0);return {canvas:renderer.domElement,left:container.scrollLeft*(renderer.domElement.width/width),width:innerWidth*(renderer.domElement.width/width)}},stats(){return {calls:renderer.info.render.calls,triangles:renderer.info.render.triangles,hotspots:hotspots.length}},dispose(){renderer.dispose()}}
}
